@isTest
private class AssetTrigger_Test3 {
    /*
 	static testMethod void test_updateAccountProductFamily(){
        
		Test.startTest();
		
		//Create test data
        TestUtility.setupConfigurationSettings();
        Account acc = TestUtility.newAccount('Test Account',null);
        insert acc;
        
		Account_Product_Family__c apf = new Account_Product_Family__c(Account__c = acc.Id);
		insert apf;
		
		acc.Account_Product_Family__c = apf.Id;
		update acc;
		
		Product2 prod = TestUtility.newProduct('Product 03');
        insert prod;
		
		
		Test.stopTest();
        
 	}
*/
}