/*------------------------------------------------------------
Author:         Denise Bacher
Company:        Salesforce.com
Description:    Test class to validate CalculateResourceSkill_SchedBatch scheduler and batch job
                Tests Excecuted:
                
                testScheduler - verifies the scheduler works
                
                testBatch - verfies that the new skill value is calculated correctly per resource

History:
<Date>          <Authors Name>      <Brief Description of Change>
05/31/2016      Denise Bacher       Initial Creation (US956)
06/24/2016      Denise Bacher       Only level resorce skills where the relate skil has "Auto Level" checked (US1310)

06/20/2018   Ryan Lambert    Remove all code / reference to FSLIS
------------------------------------------------------------*/
@isTest
private class CalculateResourceSkill_SchedBatch_Test {

}