/*------------------------------------------------------------
Author: Mani Sundaresan

Description: Generic Class to throw exceptions in apex class

History:
<Date>          <Authors Name>      <Brief Description of Change>
07/17/2018      Mani Sundaresan      Initial Creation (US-0004314)
------------------------------------------------------------*/
public class RuntimeException extends Exception {

}