/*------------------------------------------------------------
Author:         Yael Perez
Company:        Salesforce.com
Description:    Test class to validate ServiceScheduler_Invocable
                Tests Excecuted:
                
                scheduleServices_autoScheduleAppointments - Verify that when autoSchedule is set to true for an appointment, the service schedules a resource.

                scheduleServices_nonAutoScheduleAppointments - Verify that when autoSchedule is set to true for an appointment, the service does not schedule a resource.
                
History:
<Date>          <Authors Name>      <Brief Description of Change>
08/15/2016      Yael Perez          Initial Creation (US1451)

06/20/2018   Ryan Lambert    Remove all code / reference to FSLIS
------------------------------------------------------------*/

@isTest
private class ServiceScheduler_Invocable_Test {
   
}