/*------------------------------------------------------------
Author:         Denise Bacher
Company:        Salesforce.com
Description:    Test class to validate ServiceResourceBuilder_Invocable
                Tests Excecuted:
                
                createServiceResourcesTest - verifies the invocable method creates the service resources

History:
<Date>          <Authors Name>      <Brief Description of Change>
05/26/2016      Denise Bacher       Initial Creation (US1059)
06/14/2016      Denise Bacher       Updated generisize creation of roles by boolean values (US1277)

06/20/2018   Ryan Lambert    Remove all code / reference to FSLIS
------------------------------------------------------------*/
@isTest
private class ServiceResourceBuilder_Invocable_Test {

}