/*------------------------------------------------------------
Author:     Mani Sundaresan
Description:  Test Class for Work Order Trigger framework Extension Class
Class:  WorkOrderTriggerActionsExt   

History:
<Date>      <Authors Name>    <Brief Description of Change>
02/16/2017  Mani Sundaresan    Initial Creation
06/19/2017  Raj Sharan         Addition of Additional Custom Settings in static 
08/04/2017  Raj Sharan         Update to include Product Source Division when defining a Product. 
27/09/2017  Krishna prasad     update case status to Resolved  US-0003409 

06/20/2018   Ryan Lambert    Remove all code / reference to FSLIS
------------------------------------------------------------*/
@isTest
private class Test_WorkOrderTriggerActionsExt{

}