/*------------------------------------------------------------
Author:         Sumit Gupta
Company:        Salesforce.com
Description:    Test class to validate VendorCredentialTracking_Invocable
                Tests Excecuted:
        
                addServiceSkillsTest - verifies the invocable method creates the Service Skills

History:
<Date>          <Authors Name>      <Brief Description of Change>
07/01/2016      Sumit Gupta         Initial Creation (US798)

06/20/2018   Ryan Lambert    Remove all code / reference to FSLIS
------------------------------------------------------------*/
@isTest
private class VendorCredentialTracking_Invocable_Test {

}